# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from PIL import Image
from input import Ui_InputWindow
import resource_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 538)
        MainWindow.setMinimumSize(QtCore.QSize(464, 538))
        MainWindow.setMaximumSize(QtCore.QSize(464, 538))
        font = QtGui.QFont()
        font.setItalic(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_Main = QtWidgets.QLabel(self.centralwidget)
        self.label_Main.setGeometry(QtCore.QRect(0, 30, 471, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(51, 106, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 106, 188, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 106, 188))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 106, 188, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 174, 176))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 47, 52, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_Main.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(36)
        font.setItalic(False)
        self.label_Main.setFont(font)
        self.label_Main.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Main.setObjectName("label_Main")
        self.label_Image = QtWidgets.QLabel(self.centralwidget)
        self.label_Image.setGeometry(QtCore.QRect(300, 120, 151, 191))
        self.label_Image.setText("")
        self.label_Image.setPixmap(QtGui.QPixmap("avatar.jpg"))
        self.label_Image.setScaledContents(True)
        self.label_Image.setObjectName("label_Image")
        self.label_paragraph = QtWidgets.QLabel(self.centralwidget)
        self.label_paragraph.setGeometry(QtCore.QRect(20, 100, 271, 231))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_paragraph.setFont(font)
        self.label_paragraph.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_paragraph.setWordWrap(True)
        self.label_paragraph.setIndent(0)
        self.label_paragraph.setObjectName("label_paragraph")
        self.label_url = QtWidgets.QLabel(self.centralwidget)
        self.label_url.setGeometry(QtCore.QRect(130, 460, 191, 18))
        self.label_url.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_url.setAlignment(QtCore.Qt.AlignCenter)
        self.label_url.setOpenExternalLinks(True)
        self.label_url.setObjectName("label_url")
        self.button_Upload = QtWidgets.QPushButton(self.centralwidget)
        self.button_Upload.setGeometry(QtCore.QRect(327, 353, 91, 31))
        self.button_Upload.setObjectName("button_Upload")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.button_Upload.clicked.connect(self.upload_handler)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_Main.setText(_translate("MainWindow", "Photo Resizer"))
        self.label_paragraph.setText(_translate("MainWindow", "Photo reizer is a free program which helps you to resize the width, length, format and size of any image acccording to the specifications provided by various government agencies"))
        self.label_url.setText(_translate("MainWindow", "www.sarkarjoli.com"))
        self.button_Upload.setText(_translate("MainWindow", "Next"))

    def upload_handler(self):
        Ui_InputWindow.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
