# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PIL import Image


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 465)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TopLabel = QtWidgets.QLabel(self.centralwidget)
        self.TopLabel.setGeometry(QtCore.QRect(150, 10, 251, 41))
    
        #font stuff
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
    
        self.TopLabel.setFont(font)
        self.TopLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TopLabel.setObjectName("TopLabel")

        self.ImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageLabel.setGeometry(QtCore.QRect(280, 110, 231, 151))
        self.ImageLabel.setAutoFillBackground(False)
        self.ImageLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ImageLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ImageLabel.setText("")
        self.ImageLabel.setPixmap(QtGui.QPixmap("hello.png"))
        self.ImageLabel.setObjectName("ImageLabel")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 300, 121, 34))
        self.pushButton.setObjectName("pushButton")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 150, 251, 82))
        self.widget.setObjectName("widget")
        self.LeftGrid = QtWidgets.QGridLayout(self.widget)
        self.LeftGrid.setContentsMargins(0, 0, 0, 0)
        self.LeftGrid.setObjectName("LeftGrid")
        self.enter_height = QtWidgets.QLabel(self.widget)
        self.enter_height.setObjectName("enter_height")
        self.LeftGrid.addWidget(self.enter_height, 1, 0, 2, 1)
        self.InputWidth = QtWidgets.QLineEdit(self.widget)
        self.InputWidth.setObjectName("InputWidth")
        self.LeftGrid.addWidget(self.InputWidth, 0, 1, 1, 1)
        self.enter_width = QtWidgets.QLabel(self.widget)
        self.enter_width.setObjectName("enter_width")
        self.LeftGrid.addWidget(self.enter_width, 0, 0, 1, 1)
        self.px_height = QtWidgets.QLabel(self.widget)
        self.px_height.setObjectName("px_height")
        self.LeftGrid.addWidget(self.px_height, 1, 2, 2, 1)
        self.px_width = QtWidgets.QLabel(self.widget)
        self.px_width.setObjectName("px_width")
        self.LeftGrid.addWidget(self.px_width, 0, 2, 1, 1)
        self.InputHeight = QtWidgets.QLineEdit(self.widget)
        self.InputHeight.setObjectName("InputHeight")
        self.LeftGrid.addWidget(self.InputHeight, 1, 1, 2, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(280, 270, 171, 92))
        self.widget1.setObjectName("widget1")
        self.InfoGrid = QtWidgets.QGridLayout(self.widget1)
        self.InfoGrid.setContentsMargins(0, 0, 0, 0)
        self.InfoGrid.setObjectName("InfoGrid")
        self.info_width = QtWidgets.QLabel(self.widget1)
        self.info_width.setObjectName("info_width")
        self.InfoGrid.addWidget(self.info_width, 1, 0, 1, 1)
        self.info_height = QtWidgets.QLabel(self.widget1)
        self.info_height.setObjectName("info_height")
        self.InfoGrid.addWidget(self.info_height, 2, 0, 1, 1)
        self.info_name = QtWidgets.QLabel(self.widget1)
        self.info_name.setObjectName("info_name")
        self.InfoGrid.addWidget(self.info_name, 0, 0, 1, 1)
        self.OutputName = QtWidgets.QLabel(self.widget1)
        self.OutputName.setText("")
        self.OutputName.setObjectName("OutputName")
        self.InfoGrid.addWidget(self.OutputName, 0, 1, 1, 1)
        self.OutputHeight = QtWidgets.QLabel(self.widget1)
        self.OutputHeight.setText("")
        self.OutputHeight.setObjectName("OutputHeight")
        self.InfoGrid.addWidget(self.OutputHeight, 2, 1, 1, 1)
        self.OutputWidth = QtWidgets.QLabel(self.widget1)
        self.OutputWidth.setText("")
        self.OutputWidth.setObjectName("OutputWidth")
        self.InfoGrid.addWidget(self.OutputWidth, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.ChangeImage)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image resizer"))
        self.TopLabel.setText(_translate("MainWindow", "Image Resizer !"))
        self.pushButton.setText(_translate("MainWindow", "Change Image"))
        self.enter_height.setText(_translate("MainWindow", "Enter the maximum height"))
        self.enter_width.setText(_translate("MainWindow", "Enter the maximum width"))
        self.px_height.setText(_translate("MainWindow", "px"))
        self.px_width.setText(_translate("MainWindow", "px"))
        self.info_width.setText(_translate("MainWindow", "width"))
        self.info_height.setText(_translate("MainWindow", "height"))
        self.info_name.setText(_translate("MainWindow", "Name"))

    def ChangeImage(self):
        filename = QFileDialog.getOpenFileName()
        self.ImageLabel.setPixmap(QtGui.QPixmap(filename[0]))
        self.ChangeInfo(filename[0])

    def ChangeInfo(self, filename):
        img = Image.open(filename)
        self.OutputName.setText(str(filename.split('/')[-1])   )
        self.OutputWidth.setText(str(img.width))
        self.OutputHeight.setText(str(img.height))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
